[project]
name = "worker-vllm-latest"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy<=2.4.2",
    "packaging",
    "setuptools",
    "torch>=2.10.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cpu"
default = true
